# #workflow

# title: Website name
# description: uploading content
# age: 30

# #array
# tags:
# -tech
# -images
# -creative

# #objects
# address:
# street: mg road
# city: Banglore
# state: KA

# #gitvalue
# vlaue: ${{env.value}}
# variable: ${{github.Variable_name}}



name: Github actio offer
on: push:
branches: [main]
jobs:
build:
runs-on: ubuntu-latest
steps:
-uses: actions/checkout@v3 
-name: Print hello world
 run: echo "hello world!" 